image: python:3.11
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run_tests:
    steps:
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
